### ISSUE TITLE
Re-implement table layout without external dependency

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#346]
- [ ] Add support for COLGROUP, COL tag, related to #339
- [x] Drop flutter_layout_grid, should fix `Intrinsics are not available for` error when [`WidgetSpan` is used within table](https://github.com/daohoangson/flutter_widget_from_html/issues/338#issuecomment-705359844).
- [x] Align baseline between cells in the same row, related to #176 
- [x] Table height should not expand, related to #310

**Comment by daohoangson** [comment]
Closing in favor of #339
